---
- hosts: bucketlist
  remote_user: root
  environment:
    DATABASE_URL: postgresql://postgres:pass@localhost:5432/bucketlist_dev
    BUCKETLIST_ENV: development

  tasks:
  - name: Install nginx, postgres and uwsgi
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - nginx
    - postgresql
    - uwsgi
  
  - name: Start nginx, postgresql and uwsgi
    service: 
      name: "{{ item }}" 
      state: started 
      enabled: true
    with_items:
    - nginx
    - postgresql
    - uwsgi
    become: yes
    become_user: root

  - name: Configure nginx
    template:
      src: templates/bucketlist
      dest: /etc/nginx/sites-available/bucketlist
    become: yes
    become_user: root
  
  - name: Add bucketlist to site-enabled
    file:
      path=/etc/nginx/sites-enabled
      src=/etc/nginx/sites-available/bucketlist
      state=link
      force=yes
    become: yes
    become_user: root
    notify:
      - Restart uwsgi
      - Restart nginx
  
  - name: Copy Postgres configurations
    template: src=templates/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    become: yes
    become_user: root
    notify:
      - Restart postgres
  
  - name: Create symlink to nodejs
    file:
      path=/usr/bin/node
      src=/usr/bin/nodejs
      state=link
      force=yes
    become: yes
    become_user: root
 
  - name: Create app folder
    file:
      path: app/
      state: directory
      mode: 0755
      owner: vagrant

  - name: Clone the bucketlist app from github
    git:
      repo: https://github.com/SProjects/bucketlist_andela.git
      dest: app/
    become: yes
    become_user: root
  
  - name: Copy app.ini configurations to virtual machine
    template:
      src=templates/app.ini dest=/home/vagrant/app/app.ini
    become: yes
    become_user: root
  
  - name: Copy wsgi.py configurations to virtual machine
    template:
      src=templates/wsgi.py dest=/home/vagrant/app/wsgi.py
    become: yes
    become_user: root

  - name: Install requirements
    command: pip install -r requirements.txt
    args:
      chdir: app/
    become: yes
    become_user: root
  
  - name: Create Postgres DB
    postgresql_db:
      name: bucketlist_dev
      state: present
    become: yes
    become_user: postgres
  
  - name: Grant user postgres access to database
    postgresql_user:
      db: bucketlist_dev
      name: postgres
      password: pass
      priv: ALL
    become: yes
    become_user: postgres
      
  - name: Run migrations
    command: python manage.py db upgrade
    args:
      chdir: app/

  - name: Create socket file
    file:
      path: /app/bucketlist.sock
      owner: root
      mode: 666
      state: touch
    become: yes
    become_user: root

  - name: Generate JS assets
    shell: |
      cd bucketlist/client
      bower install
      npm install
      npm run build
    args:
      chdir: app/
      executable: /bin/bash
    become: yes
    become_user: root

  handlers:
    - name: Restart postgres
      service: name=postgresql state=restarted
    
    - name: Restart uwsgi
      service: name=uwsgi state=restarted
    
    - name: Restart nginx
      service: name=nginx state=restarted
