---
- hosts: bucketlist
  become_user: root
  become: yes
  environment:
    DATABASE_URL: postgresql://postgres:pass@localhost:5432/bucketlist_dev
    BUCKETLIST_ENV: development

  tasks:
  - name: Install nginx, postgres and uwsgi
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - nginx
    - postgresql
    - uwsgi
  
  - name: Install and start nginx, postgresql and uwsgi
    service: 
      name: "{{ item }}" 
      state: started 
      enabled: true
    with_items:
    - nginx
    - postgresql
    - uwsgi
  
  - name: Disable default nginx site
    file: 
      path: /etc/nginx/sites-enabled/default 
      state: absent
    notify:
      - Restart nginx

  - name: Configure nginx
    template:
      src: templates/bucketlist
      dest: /etc/nginx/sites-available/bucketlist
  
  - name: Add bucketlist to site-enabled
    file:
      path=/etc/nginx/sites-enabled/bucketlist
      src=/etc/nginx/sites-available/bucketlist
      state=link
      force=yes
    notify:
      - Restart nginx
  
  - name: Copy Postgres configurations
    template: src=templates/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    notify:
      - Restart postgres
  
  - name: Create app folder
    file:
      path: app/
      state: directory
      mode: 0755
      owner: vagrant

  - name: Clone the bucketlist app from github
    git:
      repo: https://github.com/SProjects/bucketlist_andela.git
      dest: app/
  
  - name: Copy app.ini configurations to virtual machine
    template:
      src=templates/app.ini dest=/home/vagrant/app/app.ini
  
  - name: Copy wsgi.py configurations to virtual machine
    template:
      src=templates/wsgi.py dest=/home/vagrant/app/wsgi.py
  
  - name: Create virtual environment and install requirements
    shell: | 
      virtualenv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install uwsgi
    args:
      chdir: app/
      executable: /bin/bash

  - name: Copy uwsgi configuration to virtual machine
    template:
      src=templates/bucketlist.conf dest=/etc/init/bucketlist.conf
    notify:
      - Restart uwsgi

  - name: Create Postgres DB
    postgresql_db:
      name: bucketlist_dev
      state: present
      login_user: postgres
      login_password: pass
    become: yes
    become_user: postgres

  - name: Grant user postgres access to database
    postgresql_user:
      db: bucketlist_dev
      name: postgres
      password: pass
      priv: ALL
      login_user: postgres
      login_password: pass
    become: yes
    become_user: postgres
      
  - name: Run migrations
    shell: | 
      source venv/bin/activate
      python manage.py db upgrade
    args:
      chdir: app/
      executable: /bin/bash

  handlers:
    - name: Restart postgres
      service: name=postgresql state=restarted
    
    - name: Restart uwsgi
      shell: | 
        sudo start bucketlist
    
    - name: Restart nginx
      service: name=nginx state=restarted
