# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

   config.vm.define "bucketlist" do |bucketlist|
       bucketlist.vm.box = "ubuntu/trusty64"
       bucketlist.vm.hostname = "bucketlist"
       bucketlist.vm.network "private_network", ip: "192.168.33.20"
       bucketlist.vm.network "forwarded_port", guest: 80, host: 8080
       bucketlist.vm.synced_folder ".", "/home/vagrant/ansible"
       bucketlist.vm.provision "shell", path: "setup.sh"
       bucketlist.vm.provision "ansible" do |ansible|
          ansible.playbook = "bucketlist.yml"
       end
   end

   config.vm.provider "virtualbox" do |v|
       v.memory = 1024
   end

end
